### ISSUE TITLE
AUX

### ISSUE THREAD

**Issue by daks01** [daks01/FAQx81#10]
HOWTO в штаткную магнитолу 81

ToDo поискать фотки

JACK 3,5
https://vk.com/wall-31295460_380361
https://vk.com/wall-31295460_440455
https://www.drive2.ru/l/459180246088874151/
https://vk.com/wall-31295460_475446
https://vk.com/wall150196019_1039
https://vk.com/wall-31295460_483627
https://www.drive2.ru/l/472659434011623784/
пример впайки в чайник и касетник от 90
https://www.drive2.ru/l/9182208/
https://vk.com/wall150196019_1039
https://vk.com/wall-31295460_380361
https://vk.com/wall-31295460_440455

USB
https://www.drive2.ru/l/467024986675085950/

КАСЕТНЫЙ АДАПТЕР
https://goo.gl/UI4tJu
https://vk.com/away.php?to=http%3A%2F%2Fwww.ebay.com%2Fitm%2F161765612395

РАСПИНОВКА
http://teletehnika.info/collection-of-sockets-autoradio/136-razyomy-amagnitol-toyota.html 
обознаения на схемах распиновки
http://teletehnika.info/collection-of-sockets-autoradio/15-razyomy-avtomagnitol-i-ix-oboznacheniya.html

ДИНАМИКИ
http://toyotapartscatalog.com/toyota/cresta-jzx81-cepzf-2-5l-24-valve-dohc-efi-atm-1988-1992-jp-4-speaker/
https://pp.vk.me/c633618/v633618527/147bb/mY8i4StBkJ8.jpg

**Comment by StasFox** [comment]
Большинство ссылок битые, остальное уже добавлено. Закрываю
