### ISSUE TITLE
перенести раздел 'Кастом лапы gx>jzx' в 'Свап -> JZ'

### ISSUE THREAD

**Issue by daks01** [daks01/FAQx81#114]
поближе к переделке балки под джей

https://daks01.github.io/FAQx81/#%D0%BA%D0%B0%D1%81%D1%82%D0%BE%D0%BC-%D0%BB%D0%B0%D0%BF%D1%8B-gxjzx

https://daks01.github.io/FAQx81/#1jz-ge-vvt-i

**Comment by StasFox** [comment]
перенёс
