### ISSUE TITLE
электровентилятор в печку от ваза

### ISSUE THREAD

**Issue by daks01** [daks01/FAQx81#121]
2111-2123 (универсальный) LFh 01230

https://luzar.ru/catalogue/elektroventilyatory/elektroventilyatory-otopitelya/elektroventilyator-otopitelya-2111-2123-lfh-01230/

почти болтон
![16126100485941783949876](https://user-images.githubusercontent.com/1611549/107116620-60011980-6896-11eb-8e07-0a250f8484d4.jpg)

**Comment by StasFox** [comment]
Добавил в #печка
