### ISSUE TITLE
Ремонт уголка спидометра

### ISSUE THREAD

**Issue by daks01** [daks01/FAQx81#122]
https://www.drive2.ru/l/583315933498475849/

**Comment by daks01** [comment]
70мм тросик
с москвича (4.1мм)
с мотоциклетный с хонды (3.9мм)
с десятки (3.9мм)

![image](https://user-images.githubusercontent.com/1611549/110114348-4fc95500-7dd6-11eb-97be-5b2d3ddc8d20.png)

![image](https://user-images.githubusercontent.com/1611549/110114387-61126180-7dd6-11eb-99bd-3e29f3218125.png)

**Comment by StasFox** [comment]
добавил в разное
