### ISSUE TITLE
карданы. размеры, передаточные на 90\100 кузовах

### ISSUE THREAD

**Issue by daks01** [daks01/FAQx81#124]
https://vk.com/wall-31295460_773812
https://vk.com/wall-31295460_773813

**Comment by daks01** [comment]
где-то была инфа по 81 кузову
имхо, для свапа полезно. в тот радел и добавлять

**Comment by daks01** [comment]
вот тут
надо добавить 
![image](https://user-images.githubusercontent.com/1611549/111121827-f9ef6c80-858e-11eb-92e3-a65c04d9408d.png)

**Comment by StasFox** [comment]
не совсем тебя понял, поэтому добавил в "скриншоты"
