### ISSUE TITLE
крышка динамика. реплика

### ISSUE THREAD

**Issue by daks01** [daks01/FAQx81#148]
https://vk.com/wall-31295460_791671

вотжеж заcранец!

**Comment by daks01** [comment]
https://vk.com/wall42765432_719

**Comment by daks01** [comment]
еще раз (тотже ли нет чел?)
https://vk.com/wall-102240790_229

**Comment by StasFox** [comment]
Да, чел тот же. К ссылке на его страницу добавил ссылку на группу
