### ISSUE TITLE
Мост. Манжета тормозного цилиндра на барабане от москвич 412

### ISSUE THREAD

**Issue by daks01** [daks01/FAQx81#159]
от [Виктора](https://www.drive2.ru/r/toyota/cresta/501318479467512859/)

потек как то рабочий тормозной цилиндр на барабане, магазины были закрыты уже, а машина нужна была, так в итоге я выяснил что манжеты внутри тормозного цилиндра идентичны размеру и форме манжета от москвич 412

![image](https://user-images.githubusercontent.com/1611549/192504909-07777694-b5e4-454e-826a-ffe0e24155ef.png)

**Comment by daks01** [comment]
https://www.drive2.ru/l/503601890240496465/

**Comment by nick-otto** [comment]
Добавил в раздел Тормоза  -> Разное
