### ISSUE TITLE
добавить ссылок про Подсветку личинки замка водительской двери

### ISSUE THREAD

**Issue by daks01** [daks01/FAQx81#162]
https://www.drive2.ru/l/632914078393701772/
https://www.drive2.ru/l/625238387720193929/
https://www.drive2.ru/l/526871954330747035/

![image](https://user-images.githubusercontent.com/1611549/203700528-a04f8a58-d202-4d76-9350-45c972247708.png)

**Comment by StasFox** [comment]
перенёс в "доп.опции", добавил ссылки
