### ISSUE TITLE
кран печки sat/ориг (от 100)

### ISSUE THREAD

**Issue by daks01** [daks01/FAQx81#68]
https://vk.com/wall-52153620_116751

Это ссылка на закрытую группу, (

**Comment by daks01** [comment]
![image](https://user-images.githubusercontent.com/1611549/112983546-43d37780-9177-11eb-868b-c3cd51bc237e.png)
![image](https://user-images.githubusercontent.com/1611549/112983581-4d5cdf80-9177-11eb-8a05-039ac39fb364.png)

**Comment by nick-otto** [comment]
Закинул в раздел Печка
