### ISSUE TITLE
литература по обслуживанию

### ISSUE THREAD

**Issue by daks01** [daks01/FAQx81#74]
https://jzxproject.com/bbs/index.php?/topic/10809-toyota-x-chassis-workshop-manual-and-wiring-guide-motherload/

ПЕРЕВОД
У них есть тонны хороших вещей здесь: http://www.ciscokids.com.au/technical/
 

Здесь похоронены соответствующие руководства: http://www.ciscokids.com.au/technical/manual/Japanese%20manuals/

 
Теперь вы можете вытащить их оттуда или посмотреть прямо на моем Google Диске здесь: https://drive.google.com/drive/folders/1IKDO1U5uq5R8Tci7o3EnI9t1crHmo-Id?usp=sharing

 
Я также скопировал zip-файлы на AWS S3 здесь:
VOL 2 = T60-> X10 1970-1972 https://s3.amazonaws.com/jzxp/RepairManuals/VOL+2.zip
VOL 4 = X10-> X30 1976-1977 гг. Https://s3.amazonaws.com/jzxp/RepairManuals/VOL+4.zip
VOL 6 = X60-> X70 1980-1984 гг. Https://s3.amazonaws.com/jzxp/RepairManuals/VOL+6.zip
VOL 7 ​​= X70-> X80 1985-1991 https://s3.amazonaws.com/jzxp/RepairManuals/VOL+7.zip
VOL 8 = X80-> X90 1992-1995 гг. Https://s3.amazonaws.com/jzxp/RepairManuals/VOL+8.zip
VOL 9 = X90 + X70 Wagon 1995-1997 гг. Https://s3.amazonaws.com/jzxp/RepairManuals/VOL+9.zip
VOL 10 = X100 + V20 Wagon 1998-2001 гг. Https://s3.amazonaws.com/jzxp/RepairManuals/VOL+10.zip

**Comment by daks01** [comment]
http://www.technical.ciscokids.com.au/technical/toyota/     These are Toyota programs used by Toyota in australia. will probobly not work with out licenses but if you can get them working let me know how and i will add an instructional manual for it. 
http://www.technical.ciscokids.com.au/technical/textbook/  Educational book's in regards to automotive learning. (aero, tuning ect)
http://www.technical.ciscokids.com.au/technical/manual/1JZ Engine/   JZ Engine manual's
http://www.technical.ciscokids.com.au/technical/manual/Cressida MX83/  92 USDM Cressida Manual
http://www.technical.ciscokids.com.au/technical/manual/Toyota Wire Harness Repair.pdf  Toyota wiring harness repair manual 
http://www.technical.ciscokids.com.au/technical/manual/Cressida MX83/Wiring Diagram/  All Cressida Wiring diagrams including wiring 7MGTE into X8 and Digital Dash into X83
http://www.technical.ciscokids.com.au/technical/manual/Supra A70 A80/   A70 Manuals Use for 7MGTE item's, and A80 is 97+ so use that for 2JZ VVTI item's 
http://www.technical.ciscokids.com.au/technical/manual/Japanese manuals/  Now all Japanese complete collection
http://www.technical.ciscokids.com.au/technical/greddyE01/  Greddy E01 firmware 
http://www.technical.ciscokids.com.au/technical/vid/ JZ special japan magazine DVD and the other is realst how to build JZ engine manual thing.

**Comment by daks01** [comment]
https://vk.com/wall-31295460_737736 длина карданов

**Comment by StasFox** [comment]
- мануалы → см. раздел ([Литература](#Литература))

**Comment by daks01** [comment]
23ce9f27d9178c8b36e5060d1518d90de0214b8d

**Comment by Saint1213** [comment]
See not ccc
